"use client";
import { useEffect,useMemo,useState } from "react";
import { Coins,Search,ShoppingCart,Sparkles,Package,Check,LockKeyhole,Loader2 } from "lucide-react";
type Item={id:number;name:string;category:string;rarity:string;price:number;stock:number;emoji:string;description:string;accent:string};
const categories=["Tümü","Rozet","Unvan","Çerçeve"];
export default function MarketPage(){
 const [items,setItems]=useState<Item[]>([]),[category,setCategory]=useState("Tümü"),[query,setQuery]=useState(""),[balance,setBalance]=useState<number|null>(null),[owned,setOwned]=useState<number[]>([]),[notice,setNotice]=useState(""),[loading,setLoading]=useState(true),[buying,setBuying]=useState<number|null>(null),[authenticated,setAuthenticated]=useState(false);
 async function load(){setLoading(true);try{const r=await fetch("/api/market",{cache:"no-store"});const d=await r.json();setItems(d.items||[]);setBalance(d.balance);setOwned(d.owned||[]);setAuthenticated(!!d.authenticated)}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>items.filter(i=>(category==="Tümü"||i.category===category)&&i.name.toLocaleLowerCase("tr").includes(query.toLocaleLowerCase("tr"))),[items,category,query]);
 async function buy(item:Item){if(!authenticated){location.href="/api/steam";return}setBuying(item.id);setNotice("");const r=await fetch("/api/market/buy",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({itemId:item.id})});const d=await r.json();setBuying(null);setNotice(d.message||d.error||"");if(r.ok)await load()}
 return <main className="min-h-screen bg-[radial-gradient(circle_at_15%_20%,rgba(8,145,178,.10),transparent_28%),#020617] px-6 pb-20 pt-32 text-white"><div className="mx-auto max-w-7xl">
 <section className="mb-9 flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div><div className="mb-3 flex items-center gap-2 text-xs font-black uppercase tracking-[.35em] text-cyan-400"><Sparkles size={15}/> RXALIENS MARKET</div><h1 className="text-4xl font-black tracking-tight sm:text-5xl">Alien Envanterini <span className="text-cyan-400">Yükselt</span></h1><p className="mt-3 max-w-2xl text-slate-400">Coinlerini profil kozmetikleri, özel unvanlar ve sınırlı koleksiyon parçaları için kullan.</p></div><div className="flex items-center gap-4 rounded-2xl border border-cyan-400/25 bg-cyan-400/[.06] px-5 py-4"><div className="rounded-xl bg-cyan-400/10 p-3 text-cyan-300"><Coins/></div><div><p className="text-xs uppercase tracking-wider text-slate-400">Bakiyen</p><p className="text-2xl font-black">{authenticated?(balance??0):"—"} <span className="text-sm text-cyan-400">Coin</span></p></div></div></section>
 <section className="mb-7 flex flex-col gap-4 rounded-2xl border border-cyan-400/15 bg-white/[.025] p-4 md:flex-row md:items-center md:justify-between"><div className="flex flex-wrap gap-2">{categories.map(c=><button key={c} onClick={()=>setCategory(c)} className={`rounded-xl px-4 py-2 text-sm font-bold ${category===c?"bg-cyan-400 text-slate-950":"bg-white/[.04] text-slate-300"}`}>{c}</button>)}</div><label className="flex items-center gap-2 rounded-xl border border-white/10 bg-black/20 px-4 py-2.5 md:w-72"><Search size={17} className="text-cyan-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Markette ara..." className="w-full bg-transparent text-sm outline-none"/></label></section>
 {notice&&<div className="mb-6 rounded-xl border border-cyan-400/25 bg-cyan-400/10 px-4 py-3 text-sm font-bold text-cyan-200">{notice}</div>}
 {loading?<div className="flex justify-center py-24 text-cyan-400"><Loader2 className="animate-spin"/></div>:<div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{filtered.map(item=>{const isOwned=owned.includes(item.id),can=authenticated&&(balance??0)>=item.price&&item.stock>0;return <article key={item.id} className={`group relative overflow-hidden rounded-3xl border border-cyan-400/15 bg-gradient-to-br ${item.accent} via-[#0b1220] to-[#070b14] p-6 transition hover:-translate-y-1 hover:border-cyan-400/35`}><div className="flex items-start justify-between"><ProductEmojiBubble emoji={item.emoji}/><span className="rounded-full border border-white/10 bg-black/20 px-3 py-1 text-[11px] font-bold uppercase tracking-wider text-slate-300">{item.rarity}</span></div><div className="mt-6"><p className="text-xs font-bold uppercase tracking-[.2em] text-cyan-400">{item.category}</p><h2 className="mt-1 text-xl font-black">{item.name}</h2><p className="mt-2 min-h-10 text-sm leading-6 text-slate-400">{item.description}</p></div><div className="mt-6 flex items-end justify-between border-t border-white/[.07] pt-5"><div><p className="flex items-center gap-1.5 text-xl font-black"><Coins size={18} className="text-cyan-400"/>{item.price}</p><p className="mt-1 flex items-center gap-1 text-xs text-slate-500"><Package size={13}/> Stok: {item.stock}</p></div><button onClick={()=>buy(item)} disabled={isOwned||buying===item.id} className={`inline-flex items-center gap-2 rounded-xl px-4 py-2.5 text-sm font-black ${isOwned?"bg-emerald-500/15 text-emerald-400":can?"bg-cyan-400 text-slate-950":"bg-white/[.05] text-slate-500"}`}>{buying===item.id?<Loader2 size={17} className="animate-spin"/>:isOwned?<><Check size={17}/>Alındı</>:!authenticated?<><ShoppingCart size={17}/>Giriş Yap</>:can?<><ShoppingCart size={17}/>Satın Al</>:<><LockKeyhole size={16}/>{item.stock<=0?"Tükendi":"Coin Yetersiz"}</>}</button></div></article>})}</div>}
 <p className="mt-8 text-center text-xs text-slate-600">Satın alımlar RXALIENS hesabına kalıcı olarak kaydedilir. Fiyat, bakiye ve stok kontrolleri sunucuda yapılır.</p></div></main>}

function ProductEmojiBubble({emoji}:{emoji:string}){
 const glyphs=Array.from((emoji||"👽").trim());
 const multi=glyphs.length>1;
 return <div className={`flex shrink-0 items-center justify-center rounded-2xl border border-white/10 bg-black/25 transition-all ${multi?"min-h-16 min-w-[5.75rem] px-3 py-2":"h-16 w-16"}`}>
  <span className={`flex items-center justify-center ${multi?"flex-row gap-1.5 text-[2rem] leading-none":"text-4xl"}`}>{glyphs.map((g,i)=><span key={`${g}-${i}`} className="inline-flex leading-none">{g}</span>)}</span>
 </div>
}
