"use client";
import Image from "next/image";
import { Crown, Medal, Trophy, Zap } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import SectionTitle from "@/components/ui/SectionTitle";

type Player={rank:number;steam_id:string;name:string;avatar?:string;rx_xp:number;level:number;currentXp:number;nextXp:number;progress:number;title_name?:string;title_emoji?:string;isMe?:boolean};
export default function Leaderboard(){
 const [players,setPlayers]=useState<Player[]>([]); const [loading,setLoading]=useState(true);
 const load=useCallback(async()=>{try{const r=await fetch(`/api/leaderboard?t=${Date.now()}`,{cache:'no-store'});const d=await r.json();setPlayers(d.players||[])}finally{setLoading(false)}},[]);
 useEffect(()=>{void load();const refresh=()=>void load();const storage=(e:StorageEvent)=>{if(e.key==="rxaliens:xp-updated")refresh()};const visible=()=>{if(document.visibilityState==="visible")refresh()};window.addEventListener("rxaliens:xp-updated",refresh);window.addEventListener("storage",storage);document.addEventListener("visibilitychange",visible);return()=>{window.removeEventListener("rxaliens:xp-updated",refresh);window.removeEventListener("storage",storage);document.removeEventListener("visibilitychange",visible)}},[load]);
 const medals=[Crown,Medal,Trophy];
 return <section id="leaderboard" className="relative overflow-hidden py-28"><div className="absolute left-1/2 top-20 h-[500px] w-[500px] -translate-x-1/2 rounded-full bg-cyan-500/10 blur-[180px]"/><div className="relative mx-auto max-w-6xl px-6"><SectionTitle badge="RXALIENS LEADERBOARD" title="En Yüksek RX Level" description="RX 100 maksimum seviye. Seviye sınırına ulaştıktan sonra da toplam XP kazanmaya devam et ve sıralamada yüksel."/>
 {loading?<p className="mt-10 text-center text-slate-500">Sıralama yükleniyor...</p>:players.length===0?<p className="mt-10 text-center text-slate-500">Henüz sıralamaya giren oyuncu yok.</p>:<>
 <div className="mt-12 grid gap-6 lg:grid-cols-3">{players.slice(0,3).map((p,i)=>{const Icon=medals[i];return <div key={p.steam_id} className={`rounded-3xl border p-6 text-center backdrop-blur-xl ${p.isMe?'border-cyan-300/60 bg-cyan-400/[.08]':'border-cyan-400/20 bg-white/[.035]'}`}><Icon className={`mx-auto ${i===0?'text-yellow-400':i===1?'text-slate-300':'text-orange-400'}`} size={34}/><Image src={p.avatar||'/images/default-avatar.png'} alt={p.name} width={72} height={72} className="mx-auto mt-4 rounded-full border-2 border-cyan-400/30"/><h3 className="mt-4 text-xl font-black">{p.name}</h3>{p.title_name&&<p className="mt-1 text-xs font-bold text-cyan-400">{p.title_emoji} {p.title_name}</p>}<div className="mt-5 flex items-center justify-center gap-2"><Zap size={17} className="text-cyan-400"/><b className="text-2xl">RX {p.level}</b></div><p className="mt-1 text-sm text-slate-500">{p.rx_xp.toLocaleString('tr-TR')} toplam XP</p><Progress p={p}/></div>})}</div>
 <div className="mt-8 overflow-hidden rounded-3xl border border-cyan-400/15 bg-white/[.025]"><div className="grid grid-cols-[70px_1fr_110px_130px] gap-3 border-b border-white/10 px-5 py-3 text-xs font-black tracking-wider text-slate-500"><span>SIRA</span><span>OYUNCU</span><span>LEVEL</span><span>TOPLAM XP</span></div>{players.map(p=><div key={p.steam_id} className={`grid grid-cols-[70px_1fr_110px_130px] items-center gap-3 border-b border-white/5 px-5 py-4 last:border-0 ${p.isMe?'bg-cyan-400/[.07]':''}`}><b className="text-cyan-400">#{p.rank}</b><div className="flex min-w-0 items-center gap-3"><Image src={p.avatar||'/images/default-avatar.png'} alt={p.name} width={38} height={38} className="rounded-full"/><div className="min-w-0"><b className="block truncate">{p.name}{p.isMe?' (Sen)':''}</b>{p.title_name&&<span className="text-xs text-slate-500">{p.title_emoji} {p.title_name}</span>}</div></div><b>RX {p.level}</b><span className="font-bold text-cyan-300">{p.rx_xp.toLocaleString('tr-TR')} XP</span></div>)}</div></>}
 </div></section>
}
function Progress({p}:{p:Player}){const isMax=p.level>=100;return <div className="mt-4">{isMax?<div className="mb-1 flex items-center justify-between text-[11px]"><span className="font-bold text-cyan-300">MAX LEVEL</span><span className="text-slate-500">Sıralama: Toplam XP</span></div>:<div className="mb-1 flex justify-between text-[11px] text-slate-500"><span>{p.currentXp.toLocaleString('tr-TR')} XP</span><span>{p.nextXp.toLocaleString('tr-TR')} XP</span></div>}<div className="h-2 overflow-hidden rounded-full bg-black/40"><div className="h-full rounded-full bg-gradient-to-r from-cyan-500 to-sky-300 transition-all" style={{width:`${isMax?100:p.progress}%`}}/></div>{isMax&&<p className="mt-2 text-[11px] text-slate-500">RX 100 tamamlandı • XP kazanmaya devam ederek liderlik sıralamasında yüksel.</p>}</div>}
